/**
 * Living HTTP API inventory for Versa - Business Admin (VBA) 0.7.x.
 * GET /api and Settings → API both render this list. Keep in lockstep with
 * src/app/api/** route handlers.
 */

export type ApiAuth =
  | "open"
  | "session"
  | "admin"
  | "admin-or-self"
  | "admin-or-assignee";

export type ApiMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export type ApiResource = {
  group: string;
  method: ApiMethod;
  path: string;
  auth: ApiAuth;
  summary: string;
};

export const API_RESOURCES: ApiResource[] = [
  {
    group: "Discovery",
    method: "GET",
    path: "/api",
    auth: "open",
    summary: "Index: version, docs links, and the full resource catalog.",
  },
  {
    group: "Discovery",
    method: "GET",
    path: "/api/health",
    auth: "open",
    summary: "Process health, package version, and database connectivity.",
  },
  {
    group: "Auth",
    method: "GET",
    path: "/api/auth/challenge",
    auth: "open",
    summary: "Proof-of-work login challenge.",
  },
  {
    group: "Auth",
    method: "POST",
    path: "/api/auth/login",
    auth: "open",
    summary: "Create a session cookie (challenge + credentials).",
  },
  {
    group: "Auth",
    method: "POST",
    path: "/api/auth/logout",
    auth: "session",
    summary: "Clear the session cookie.",
  },
  {
    group: "Auth",
    method: "GET",
    path: "/api/auth/session",
    auth: "session",
    summary: "Current session user.",
  },
  {
    group: "Catalog",
    method: "GET",
    path: "/api/catalog",
    auth: "session",
    summary: "Object catalog index (schema for agents and the Records Editor).",
  },
  {
    group: "Catalog",
    method: "GET",
    path: "/api/catalog/objects",
    auth: "session",
    summary: "List catalog objects.",
  },
  {
    group: "Catalog",
    method: "GET",
    path: "/api/catalog/objects/{object_api_name}",
    auth: "session",
    summary: "One catalog object with fields.",
  },
  {
    group: "Catalog",
    method: "GET",
    path: "/api/catalog/fields",
    auth: "session",
    summary: "List fields. Filter: object={object_api_name}.",
  },
  {
    group: "Catalog",
    method: "POST",
    path: "/api/catalog/fields",
    auth: "admin",
    summary: "Extend an object with a custom field (c_ namespace).",
  },
  {
    group: "Catalog",
    method: "PATCH",
    path: "/api/catalog/fields/{object_api_name}/{api_name}",
    auth: "admin",
    summary: "Update a field definition.",
  },
  {
    group: "Catalog",
    method: "DELETE",
    path: "/api/catalog/fields/{object_api_name}/{api_name}",
    auth: "admin",
    summary: "Hide (not delete) a system field; remove a custom field.",
  },
  {
    group: "Catalog",
    method: "GET",
    path: "/api/catalog/layouts",
    auth: "session",
    summary: "List layouts. Filters: object, type=detail|edit|list.",
  },
  {
    group: "Catalog",
    method: "POST",
    path: "/api/catalog/layouts",
    auth: "admin",
    summary: "Save a layout overlay.",
  },
  {
    group: "Catalog",
    method: "GET",
    path: "/api/catalog/value-sets",
    auth: "session",
    summary: "List value sets.",
  },
  {
    group: "Catalog",
    method: "POST",
    path: "/api/catalog/value-sets",
    auth: "admin",
    summary: "Create a value set.",
  },
  {
    group: "Catalog",
    method: "GET",
    path: "/api/catalog/value-sets/{api_name}",
    auth: "session",
    summary: "One value set with entries.",
  },
  {
    group: "Catalog",
    method: "POST",
    path: "/api/catalog/value-sets/{api_name}",
    auth: "admin",
    summary: "Add or replace value-set entries.",
  },
  {
    group: "Catalog",
    method: "DELETE",
    path: "/api/catalog/value-sets/{api_name}",
    auth: "admin",
    summary: "Remove a custom value set.",
  },
  {
    group: "Catalog",
    method: "GET",
    path: "/api/catalog/record-types",
    auth: "session",
    summary: "List record types. Filters: parent_kind, parent_api_name, include_inactive=1.",
  },
  {
    group: "Catalog",
    method: "POST",
    path: "/api/catalog/record-types",
    auth: "admin",
    summary: "Create a record type.",
  },
  {
    group: "Catalog",
    method: "GET",
    path: "/api/catalog/record-types/{api_name}",
    auth: "session",
    summary: "One record type.",
  },
  {
    group: "Catalog",
    method: "PATCH",
    path: "/api/catalog/record-types/{api_name}",
    auth: "admin",
    summary: "Update a record type.",
  },
  {
    group: "Catalog",
    method: "DELETE",
    path: "/api/catalog/record-types/{api_name}",
    auth: "admin",
    summary: "Deactivate a record type.",
  },
  {
    group: "Records",
    method: "GET",
    path: "/api/records",
    auth: "session",
    summary: "List records. Filters: type, parent_kind, parent.",
  },
  {
    group: "Records",
    method: "POST",
    path: "/api/records",
    auth: "admin",
    summary: "Create a record (header + lines + optional relations).",
  },
  {
    group: "Records",
    method: "GET",
    path: "/api/records/{id}",
    auth: "session",
    summary: "One record.",
  },
  {
    group: "Records",
    method: "PATCH",
    path: "/api/records/{id}",
    auth: "admin",
    summary: "Update a record.",
  },
  {
    group: "Records",
    method: "DELETE",
    path: "/api/records/{id}",
    auth: "admin",
    summary: "Delete a record.",
  },
  {
    group: "Records",
    method: "GET",
    path: "/api/records/{id}/relations",
    auth: "session",
    summary: "Inbound and outbound relations with display names.",
  },
  {
    group: "Organizations",
    method: "GET",
    path: "/api/organizations",
    auth: "session",
    summary: "List organizations. Filter: org_type.",
  },
  {
    group: "Organizations",
    method: "POST",
    path: "/api/organizations",
    auth: "admin",
    summary: "Create an organization.",
  },
  {
    group: "Organizations",
    method: "GET",
    path: "/api/organizations/{id}",
    auth: "session",
    summary: "One organization.",
  },
  {
    group: "Organizations",
    method: "PATCH",
    path: "/api/organizations/{id}",
    auth: "admin",
    summary: "Update an organization.",
  },
  {
    group: "Organizations",
    method: "DELETE",
    path: "/api/organizations/{id}",
    auth: "admin",
    summary: "Delete an organization.",
  },
  {
    group: "Organizations",
    method: "GET",
    path: "/api/organizations/{id}/lines",
    auth: "session",
    summary: "Organization line rows (integrations, appointments, …).",
  },
  {
    group: "Organizations",
    method: "POST",
    path: "/api/organizations/{id}/lines",
    auth: "admin",
    summary: "Add an organization line.",
  },
  {
    group: "Organizations",
    method: "PATCH",
    path: "/api/organizations/{id}/lines",
    auth: "admin",
    summary: "Update an organization line.",
  },
  {
    group: "Organizations",
    method: "DELETE",
    path: "/api/organizations/{id}/lines",
    auth: "admin",
    summary: "Delete an organization line.",
  },
  {
    group: "Work",
    method: "GET",
    path: "/api/users",
    auth: "session",
    summary: "List users. Filter: type=human|agent.",
  },
  {
    group: "Work",
    method: "POST",
    path: "/api/users",
    auth: "admin",
    summary: "Create a user.",
  },
  {
    group: "Work",
    method: "GET",
    path: "/api/users/{id}",
    auth: "session",
    summary: "One user.",
  },
  {
    group: "Work",
    method: "PATCH",
    path: "/api/users/{id}",
    auth: "admin-or-self",
    summary: "Update a user. Members cannot change role/type/status.",
  },
  {
    group: "Work",
    method: "GET",
    path: "/api/projects",
    auth: "session",
    summary: "List business projects.",
  },
  {
    group: "Work",
    method: "POST",
    path: "/api/projects",
    auth: "admin",
    summary: "Create a project.",
  },
  {
    group: "Work",
    method: "GET",
    path: "/api/projects/{id}",
    auth: "session",
    summary: "One project.",
  },
  {
    group: "Work",
    method: "PATCH",
    path: "/api/projects/{id}",
    auth: "admin",
    summary: "Update a project (data JSON merged).",
  },
  {
    group: "Work",
    method: "GET",
    path: "/api/tasks",
    auth: "session",
    summary: "List tasks. Filters: status, projectId, priority, assignee, q.",
  },
  {
    group: "Work",
    method: "POST",
    path: "/api/tasks",
    auth: "admin",
    summary: "Create a task.",
  },
  {
    group: "Work",
    method: "GET",
    path: "/api/tasks/{id}",
    auth: "session",
    summary: "One task.",
  },
  {
    group: "Work",
    method: "PATCH",
    path: "/api/tasks/{id}",
    auth: "admin-or-assignee",
    summary: "Update a task. Assignee may only change status.",
  },
  {
    group: "Work",
    method: "GET",
    path: "/api/products",
    auth: "session",
    summary: "List products.",
  },
  {
    group: "Work",
    method: "POST",
    path: "/api/products",
    auth: "admin",
    summary: "Create a product.",
  },
  {
    group: "Work",
    method: "GET",
    path: "/api/products/{id}",
    auth: "session",
    summary: "One product.",
  },
  {
    group: "Work",
    method: "PATCH",
    path: "/api/products/{id}",
    auth: "admin",
    summary: "Update a product.",
  },
  {
    group: "Work",
    method: "GET",
    path: "/api/integrations",
    auth: "session",
    summary: "List integrations (optional seed).",
  },
  {
    group: "Work",
    method: "GET",
    path: "/api/element-config/{element}",
    auth: "session",
    summary: "Division configuration (appointed head and deputy).",
  },
  {
    group: "Work",
    method: "PUT",
    path: "/api/element-config/{element}",
    auth: "admin",
    summary: "Save division configuration.",
  },
  {
    group: "Settings",
    method: "GET",
    path: "/api/settings/system",
    auth: "session",
    summary: "Modes, operator menu, and public menu.",
  },
  {
    group: "Settings",
    method: "PUT",
    path: "/api/settings/system",
    auth: "admin",
    summary: "Update modes and menus.",
  },
  {
    group: "Settings",
    method: "GET",
    path: "/api/settings/branding",
    auth: "session",
    summary: "Brand name, color, logo, and sky animation.",
  },
  {
    group: "Settings",
    method: "PUT",
    path: "/api/settings/branding",
    auth: "admin",
    summary: "Save branding and sky animation.",
  },
  {
    group: "Settings",
    method: "GET",
    path: "/api/settings/public-content",
    auth: "session",
    summary: "Cycle-strip and public homepage copy.",
  },
  {
    group: "Settings",
    method: "PUT",
    path: "/api/settings/public-content",
    auth: "admin",
    summary: "Save public homepage copy.",
  },
  {
    group: "Settings",
    method: "GET",
    path: "/api/settings/sample-data",
    auth: "session",
    summary: "Sample-data pack status.",
  },
  {
    group: "Settings",
    method: "POST",
    path: "/api/settings/sample-data",
    auth: "admin",
    summary: "Insert or delete ba_sample: rows.",
  },
  {
    group: "Settings",
    method: "GET",
    path: "/api/settings/agent-packages",
    auth: "session",
    summary: "Installed agent packages (D5).",
  },
  {
    group: "Settings",
    method: "POST",
    path: "/api/settings/agent-packages",
    auth: "admin",
    summary: "Install or uninstall an agent package.",
  },
  {
    group: "Public",
    method: "GET",
    path: "/api/public/business",
    auth: "open",
    summary: "Public business profile.",
  },
  {
    group: "Public",
    method: "GET",
    path: "/api/public/services",
    auth: "open",
    summary: "Public services list.",
  },
  {
    group: "Public",
    method: "GET",
    path: "/api/public/products",
    auth: "open",
    summary: "Public products list.",
  },
  {
    group: "Public",
    method: "GET",
    path: "/api/public/staff",
    auth: "open",
    summary: "Public staff list.",
  },
  {
    group: "Public",
    method: "GET",
    path: "/api/public/knowledge-articles",
    auth: "open",
    summary: "Public knowledge facet.",
  },
  {
    group: "Public",
    method: "GET",
    path: "/api/public/metrics",
    auth: "open",
    summary: "Public metrics facet.",
  },
  {
    group: "Public",
    method: "GET",
    path: "/api/public/system-landscape",
    auth: "open",
    summary: "Public System Landscape facet.",
  },
  {
    group: "Public",
    method: "GET",
    path: "/api/public/support-tickets",
    auth: "open",
    summary: "Public support facet (Demo mode).",
  },
];

export const API_DOCS = {
  operator: "/settings?tab=api",
  contract: "docs/production/state/state_api_contract.md",
  ops_manual: "docs/ops/BUSINESS_ADMIN_OPS_MANUAL.md",
  conventions: {
    protocol: "HTTP JSON",
    list_envelope: "{ data: [...], count: N }",
    error_shape: "{ error: { code, message } }",
    status_codes: [200, 201, 400, 401, 403, 404, 409, 500, 501],
  },
} as const;

export function apiIndexPayload(version: string) {
  const endpoints: Record<string, string> = {};
  for (const row of API_RESOURCES) {
    const key = `${row.method} ${row.path}`;
    endpoints[key] = row.summary;
  }
  return {
    name: "Versa - Business Admin API",
    version,
    docs: {
      operator: API_DOCS.operator,
      contract: API_DOCS.contract,
      ops_manual: API_DOCS.ops_manual,
    },
    conventions: API_DOCS.conventions,
    resources: API_RESOURCES,
    endpoints,
  };
}
